apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-rabbitmq-depl
  labels:
    app: vpro-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpro-rabbitmq
  template:
    metadata:
      labels:
        app: vpro-rabbitmq
    spec:
      containers:
      - name: vpro-rabbitmq
        image: rabbitmq
        ports:
        - containerPort: 15672
          name: rabbitmq-port
      env:
      - name: RABBITMQ_DEFAULT_PASS
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: rmq-pass
      - name: RABBITMQ_DEFAULT_USER
        value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: vprormq
spec:
  selector:
    app: vpro-rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: rabbitmq-port
  type: ClusterIP