apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: masology/vprofileapp:latest
        ports:
        - containerPort: 8080
          name: vproapp-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: guest
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
          #command: ['sh', '-c', 'sleep 2']
        - name: init-memcache
          image: busybox
          command: ['sh', '-c', 'until nslookup vprocache01.default.svc.cluster.local; do echo waiting for memcache; sleep 2; done;']
          #command: ['sh', '-c', 'sleep 2']
---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: vproapp-port
  type: LoadBalancer


